### GET Door status 

GET http://localhost:3000/api/door/USER-CTRL-1
Authorization: API-KEY-123456


### PUT new state from a controller
PUT http://localhost:3000/api/door/USER-CTRL-1
Authorization: API-KEY-123456
Content-Type: application/json

{
  "status": "ctrl_closed"
}

### PUT new state from a controller
PUT http://localhost:3000/api/door/USER-CTRL-1
Authorization: API-KEY-123456
Content-Type: application/json

{
  "status": "ctrl_open"
}


### PUT new state from a controller
PUT http://localhost:3000/api/door/USER-CTRL-1
Authorization: API-KEY-123456
Content-Type: application/json

{
  "status": "ctrl_moving"
}
