### POST new state from a controller

POST http://localhost:3000/api/door
Content-Type: application/json

{
  "controllerId": "1",
  "status": "open_complete"
}

### Simulates a controller getting states to work on

GET http://localhost:3000/api/controller/command/1
